name: Hello workflow

on: 
  push:
    branches:
      - main
      - prod
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        type: environment
        required: true

# env:
#   TMP: ${{ inputs.environment == 'dev' && 'tmp-dev' || 'tmp-prod' }}

jobs:
  be-setup-dev:
    name: Hello job
    runs-on: ubuntu-latest
    environment: dev
    env:
      TMP: tmp-dev
    steps:
      - run: echo "Hello job in env=$ENVIRONMENT!"
  be-setup-prod:
    name: Hello job
    runs-on: ubuntu-latest
    environment: prod
    env:
      TMP: tmp-prod
    steps:
      - run: echo "Hello job in env=$ENVIRONMENT!"