name: Hello workflow

on: 
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        type: environment
        required: true

env:
  ENVIRONMENT: ${{ inputs.environment }}

jobs:
  hello:
    name: Hello job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello job in env $ENVIRONMENT!"
