name: Hello workflow

on: 
  push:
    branches:
      - main
    # paths-ignore:
    #   - '.github/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        type: environment
        required: true

jobs:
  tmp:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Secret is = $MY_SECRET"
  be-setup-dev:
    needs: tmp
    if: ${{ inputs.environment == '' || inputs.environment == 'dev' }}
    name: Hello dev job
    uses: ./.github/workflows/reusable-flow.yml
    with:
      environment: 'dev'
  be-setup-prod:
    if: inputs.environment == 'prod'
    name: Hello prod job
    uses: ./.github/workflows/reusable-flow.yml
    with:
      environment: 'prod'

    