name: Hello workflow

on: 
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        type: environment
        required: true

env:
  TMP: ${{ inputs.environment == 'dev' && 'tmp-dev' || (inputs.environment == 'prod' && 'tmp-prod' || 'tmp-stage') }}

jobs:
  hello:
    name: Hello job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello job in env=$ENVIRONMENT!"
