name: Hello workflow

on: 
  push:
    branches:
      - main
    # paths-ignore:
    #   - '.github/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        type: environment
        required: true

jobs:
  
  tmp:
    name: Tmp
    runs-on: ubuntu-latest
    environment: dev
    env:
      ECR_ROLE: ${{ secrets.ECR_ROLE }}
    steps:
      - name: Dump ECR_ROLE
        run: echo ECR_ROLE is $ECR_ROLE


  # be-setup-dev:
  #   # if: ${{ inputs.environment == '' || inputs.environment == 'dev' }}
  #   name: Hello dev job
  #   uses: ./.github/workflows/reusable-flow.yml
  #   with:
  #     environment: 'dev'
  #   secrets:
  #     ECR_ROLE: ${{ secrets.ECR_ROLE }}
  #   # secrets: inherit
  # be-setup-prod:
  #   # if: inputs.environment == 'prod'
  #   name: Hello prod job
  #   uses: ./.github/workflows/reusable-flow.yml
  #   with:
  #     environment: 'prod'
  #   secrets:
  #     ECR_ROLE: ${{ secrets.ECR_ROLE }}
    