name: Hello workflow

on: 
  push:
    branches:
      - main
    # paths-ignore:
    #   - '.github/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        type: environment
        required: true

env:
  ENVIRONMENT: ${{ inputs.environment == '' && 'dev' || inputs.environment  }}   

jobs:

  # tmp:
  #   runs-on: ubuntu-latest
  #   env:
  #     TMP: ${{ secrets.ECR_ROLE }}
  #   steps:
  #     - name: Dump ECR_ROLE
  #       run: |
  #         echo ECR_ROLE is $ECR_ROLE
  #         echo ECR_ROLE = ${{ secrets.ECR_ROLE }}
  #         echo $TMP $TMP1


  be-setup-dev:
   if: $ENVIRONMENT == 'dev'
    name: Hello dev job
    uses: ./.github/workflows/reusable-flow.yml
    with:
      environment: $ENVIRONMENT
    secrets: inherit
  be-setup-prod:
    if: $ENVIRONMENT == 'prod'
    name: Hello prod job
    uses: ./.github/workflows/reusable-flow.yml
    with:
      environment: $ENVIRONMENT
    secrets: inherit