name: Hello workflow

on: 
  push:
    branches:
      - main
  # workflow_dispatch:
  #   inputs:
  #     environment:
  #       description: 'Choose environment'
  #       type: environment
  #       required: true

env:
  TMP: ${{ inputs.environment == 'dev' && 'tmp-dev' || 'tmp-prod' }}

jobs:
  be-setup-dev:
    name: Hello dev job
    runs-on: ubuntu-latest
    # environment: dev
    env:
      TMP: tmp-dev
    steps:
      - name: Setup be parameters
        run: echo "Hello dev job in env=$TMP!"
  be-setup-prod:
    name: Hello prod job
    runs-on: ubuntu-latest
    environment: prod
    env:
      TMP: tmp-prod
    steps:
      - name: Setup be parameters
        run: echo "Hello prod job in env=$TMP!"