name: Hello workflow

on: 
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true 

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello workflow!"