name: Hello reusable workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: 'dev'
        required: true

concurrency:
  group: ${{ inputs.environment }}
  cancel-in-progress: true

env:
  TMP: ${{ inputs.environment }}latest

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Reusable job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::557104287276:role/GitHubECRRole
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push Docker Image to Amazon ECR
        run: |
          docker build -t hello -t 557104287276.dkr.ecr.eu-central-1.amazonaws.com/hello:latest .
          docker push 557104287276.dkr.ecr.eu-central-1.amazonaws.com/hello:latest