name: Hello reusable workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: 'dev'
        required: true
      ecr_role:
        type: string
        required: true  

# concurrency:
#   group: ${{ inputs.environment }}
#   cancel-in-progress: true

env:
  TMP: ${{ inputs.environment }}latest

permissions:
  id-token: write
  contents: read

jobs:
  tmp:
    name: Tmp sleep 4
    runs-on: ubuntu-latest
    concurrency:
      group: test-${{ inputs.environment }}
      cancel-in-progress: true
    steps:
      - run: echo "tmp"
  build:
    needs: tmp
    name: Reusable job
    runs-on: ubuntu-latest
    concurrency: build-${{ inputs.environment }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      # - name: Build and push Docker image to Amazon ECR
      #   run: |
      #     docker build -t hello -t 557104287276.dkr.ecr.eu-central-1.amazonaws.com/hello:latest .
      #     docker push 557104287276.dkr.ecr.eu-central-1.amazonaws.com/hello:latest
      # - name: Build docker image
      #   run: |
      #     docker images
      #     docker build -t hello .
      # - name: Check docker image
      #   run: docker images
