name: Hello reusable workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: 'dev'
        required: true

concurrency:
  group: ${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  build:
    name: Reusable job
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello reusable job in ${{ inputs.environment }} environment!"
          echo "BUILD_NUMBER=${BUILD_NUMBER}"
          echo "GITHUB_RUN_ID=${GITHUB_RUN_ID}, GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}"
          docker ps